// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4NpQdXOdCu9Jhh2TMw7UYVnZuhqqjkGM',
    appId: '1:375673341679:web:e790b1143dc8003cf4bd1a',
    messagingSenderId: '375673341679',
    projectId: 'jewelry-shopping-app',
    authDomain: 'jewelry-shopping-app.firebaseapp.com',
    storageBucket: 'jewelry-shopping-app.firebasestorage.app',
    measurementId: 'G-LEBWLVJMCW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzY2zZ4t44Lv9gGA-Zd2cOaYuvXLrjfJI',
    appId: '1:375673341679:android:401d236a101f776ef4bd1a',
    messagingSenderId: '375673341679',
    projectId: 'jewelry-shopping-app',
    storageBucket: 'jewelry-shopping-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3swN5Ftpemduf3K7OSmV_dDsDYDyjHHY',
    appId: '1:375673341679:ios:69f6423c5e588d31f4bd1a',
    messagingSenderId: '375673341679',
    projectId: 'jewelry-shopping-app',
    storageBucket: 'jewelry-shopping-app.firebasestorage.app',
    iosBundleId: 'com.example.jewelryShoppingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3swN5Ftpemduf3K7OSmV_dDsDYDyjHHY',
    appId: '1:375673341679:ios:69f6423c5e588d31f4bd1a',
    messagingSenderId: '375673341679',
    projectId: 'jewelry-shopping-app',
    storageBucket: 'jewelry-shopping-app.firebasestorage.app',
    iosBundleId: 'com.example.jewelryShoppingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4NpQdXOdCu9Jhh2TMw7UYVnZuhqqjkGM',
    appId: '1:375673341679:web:379586ebe88d0b8ef4bd1a',
    messagingSenderId: '375673341679',
    projectId: 'jewelry-shopping-app',
    authDomain: 'jewelry-shopping-app.firebaseapp.com',
    storageBucket: 'jewelry-shopping-app.firebasestorage.app',
    measurementId: 'G-H7HCD4RG6K',
  );
}
